version: "3.8"

x-app: &default-app
  build: .
  volumes:
    - .:/home/appuser
  depends_on:
    - "redis"

services:
  web:
    <<: *default-app
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      DEV_MODE: 1
  worker:
    <<: *default-app
    command: celery -A django_docker worker -l "${CELERY_LOG_LEVEL:-info}"
  redis:
    image: "redis:alpine"
