version: "3"

x-app: &default-app
  build: .
  volumes:
    - .:/home/appuser
  depends_on:
    - "redis"

services:
  web:
    <<: *default-app
    image: moonshadow/django-docker:${IMAGE_TAG:-latest}
    command: python3 manage.py runserver 0.0.0.0:8000
    # command: [
    #     "gunicorn",
    #     "--worker-class=gthread",
    #     "--workers=4",
    #     "--threads=8",
    #     "--log-file=-",
    #     "-b",
    #     "0.0.0.0:8000",
    #     "django_docker.wsgi",
    #   ]
    ports:
      - "8000:8000"
    environment:
      DEV_MODE: 1
  worker:
    <<: *default-app
    command: celery -A django_docker worker -l "${CELERY_LOG_LEVEL:-info}"
  redis:
    image: "redis:alpine"
