x-app: &default-app
  build: .
  volumes:
    - .:/home/appuser
  depends_on:
    - "redis"

services:
  web:
    <<: *default-app
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    command: pytest tests
